name: Reusable Publish Python

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.11'
      package-dir:
        required: false
        type: string
        default: '.'
      upload-url:
        required: false
        type: string
        default: 'https://pkgs.dev.azure.com/sigmatiq/_packaging/Sigmatiq/pypi/upload/'
    secrets:
      AZURE_ARTIFACTS_PAT:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Build wheel and sdist
        working-directory: ${{ inputs.package-dir }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build

      - name: Publish to Azure Artifacts PyPI
        working-directory: ${{ inputs.package-dir }}
        env:
          TWINE_USERNAME: az
          TWINE_PASSWORD: ${{ secrets.AZURE_ARTIFACTS_PAT }}
          TWINE_REPOSITORY_URL: ${{ inputs.upload-url }}
        run: |
          python -m pip install twine
          python -m twine upload --non-interactive dist/*
